myspace/lists/forms.py
from flask_wtf import FlaskForm 
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired

class ItemForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = StringField('Content') 
    add = SubmitField('Add')
    update = SubmitField('Update')

myspace/videos/forms.py
from flask_wtf import FlaskForm 
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired

class VideoForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    search = StringField('Search')
    url = StringField('URL')
    add = SubmitField('Add')
    update = SubmitField('Update')

myspace/lists/routes.py
from flask import Blueprint, render_template, flash, redirect, url_for, abort, request
from flask_login import login_required, current_user
from myspace.models import Item
from myspace.lists.forms import ItemForm 
from myspace import db

lists = Blueprint('lists', __name__)

@lists.route("/list", methods = ['GET', 'POST'])
@login_required
def list_items():
    reminders = Item.query.order_by(Item.time_posted.desc())
    print(reminders)
    return render_template('list.html', title='List', reminders=reminders)

@lists.route("/list/new", methods = ['GET', 'POST'])
@login_required
def new_item():
    form = ItemForm()
    if form.validate_on_submit():
        item = Item(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(item)
        db.session.commit()
        flash('Your item has been created!', 'success')
        return redirect(url_for('lists.list_items'))
    return render_template('create_item.html', title='New Item', form=form)

@lists.route("/list/<int:item_id>/update", methods= ['GET', 'POST'])
@login_required
def update_item(item_id):
    reminder = Item.query.get_or_404(item_id)
    if reminder.author != current_user:
        #403 response is the http response for a prohibited route
        abort(403)
    form = ItemForm()
    if form.validate_on_submit():
        reminder.title = form.title.data
        reminder.content = form.content.data 
        db.session.commit()
        flash('Your post has been updated!','success')
        return redirect(url_for('lists.list_items'))
    elif request.method == 'GET':
        form.title.data = reminder.title
        form.content.data = reminder.content 
    return render_template('create_item.html', title='Update Item', form=form, legend='Update Reminder')

@lists.route("/list/<int:item_id>/delete", methods = ['GET', 'POST'])
@login_required
def delete_item(item_id):
    reminder = Item.query.get_or_404(item_id)
    print(reminder)
    if reminder.author != current_user:
    #403 response is the http response for a prohibited route
        abort(403)
    db.session.delete(reminder)
    db.session.commit()
    flash('Your post has been deleted!','success')
    return redirect(url_for('lists.list_items'))    

myspace/users/routes.py
from flask import Blueprint, redirect, url_for, render_template, flash, request
from flask_login import login_user, current_user, logout_user, login_required
from myspace.users.forms import RegistrationForm, LoginForm
from myspace import bcrypt, db
from myspace.models import User

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = RegistrationForm()

    if form.validate_on_submit():
        hashed_pw = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user = User(username=form.username.data,
                    email=form.email.data, password=hashed_pw)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in.', 'success')
        return redirect(url_for('users.login'))

    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('lists.list_items'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            # will return the next page if it exists, if it doesn't exist it's none
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('lists.list_items'))
        else:
            flash('Login Unsuccessful. Please check email and password.', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

myspace/videos/routes.py
from flask import render_template, Blueprint, url_for, redirect, flash
from flask_login import login_user, current_user, logout_user, login_required
from myspace.videos.forms import VideoForm
from myspace.models import Video
from myspace import db
import re
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
from myspace.config import Config

DEVELOPER_KEY = Config.DEVELOPER_KEY
YOUTUBE_API_SERVICE_NAME = 'youtube'
YOUTUBE_API_VERSION = 'v3'

videos = Blueprint('videos', __name__)


@videos.route("/video")
def temp():
    videos = Video.query.all()
    if videos:
        return redirect(url_for('videos.video', video_id=0))
    return redirect(url_for('videos.new_video'))


@videos.route("/video/<int:video_id>")
def video(video_id=0):
    videos = Video.query.all()
    count = (len(videos))
    return render_template('video.html', videos=videos, video_id=video_id, count=count)


@videos.route("/video/new", methods=['GET', 'POST'])
@login_required
def new_video():
    form = VideoForm()
    if form.validate_on_submit():
        if form.search.data:
            video_id = youtube_search(form.search.data)
        if form.url.data:
            input_url = form.url.data
            match = re.search(r"watch\?v=(.*)", input_url)
            video_id = match.group(1)
        string = "https://www.youtube.com/embed/"
        output_url = string + video_id
        video = Video(name=form.name.data, url=output_url, author=current_user)
        db.session.add(video)
        db.session.commit()
        flash('Your video has been added!', 'success')
        return redirect(url_for('videos.temp'))
    return render_template('create_video.html', title='New Video', form=form)


@videos.route("/video/<int:video_id>/delete", methods=['GET', 'POST'])
@login_required
def delete_video(video_id):
    video = Video.query.get_or_404(video_id)
    if video.author != current_user:
        # 403 response is the http response for a prohibited route
        abort(403)
    db.session.delete(video)
    db.session.commit()
    flash('Your video has been deleted!', 'success')
    return redirect(url_for('videos.temp'))


def youtube_search(options):
    youtube = build(YOUTUBE_API_SERVICE_NAME,
                    YOUTUBE_API_VERSION, developerKey=DEVELOPER_KEY)

    search_response = youtube.search().list(
        q=options, part='id,snippet', maxResults='5').execute()

    videos = []
    channels = []
    playlists = []

    return search_response.get('items', [])[0]['id']['videoId']

myspace/templates/create_item.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <!-- since the action is "" empty string, if you try to post the form to the same link, but the link does not accept the data, it is going to be an error -->
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <!-- fieldset is to group related elements in a form -->
        <!-- legend defines caption for the fieldset -->
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                {{ form.title(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.title.errors %}
                    <span> {{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.title(class="form-control form-control-lg") }}
                {% endif %} </div>
            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                {{ form.content(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.content.errors %}
                    <span> {{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.content(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {% if legend == 'Update Reminder' %}
                {{ form.update(class="btn btn-outline-info") }}
            {% else %}
                {{ form.add(class="btn btn-outline-info") }}
            {% endif %}

        </div>
    </form>
</div>
{% endblock content %}

myspace/templates/create_video.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <!-- since the action is "" empty string, if you try to post the form to the same link, but the link does not accept the data, it is going to be an error -->
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <!-- fieldset is to group related elements in a form -->
        <!-- legend defines caption for the fieldset -->
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div>You only need to input one. Either "Search" or "URL".</div>
            <br>
            <div class="form-group">
                <strong>{{ form.name.label(class="form-control-label") }}</strong>
                <p>(Name that will be used as reference on your videos page)</p>
                {% if form.name.errors %}
                {{ form.name(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.name.errors %}
                    <span> {{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.name(class="form-control form-control-lg") }}
                {% endif %} </div>
            <div class="form-group">
                <strong>{{ form.search.label(class="form-control-label") }}</strong>
                <p>(Name of the video that you would like to watch)</p>
                {% if form.search.errors %}
                {{ form.search(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.search.errors %}
                    <span> {{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.search(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                <strong>{{ form.url.label(class="form-control-label") }}</strong>
                <p>(Link of the video that you would like to watch)</p>
                {% if form.url.errors %}
                {{ form.url(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.url.errors %}
                    <span> {{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.url(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">

            {{ form.add(class="btn btn-outline-info") }}

        </div>
    </form>
</div>
{% endblock content %}

myspace/templates/home.html
{% extends "layout.html" %}
{% block content %}
    <h1>There is currently no home content right now. Please click the above tabs.</h1>
{% endblock content %}

myspace/templates/layout.html
{# this is called templated inheritance so that changes only need to be made once #}

<!DOCTYPE html>
<html>

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
    <title>Personal Bubble - {{ title }}</title>
    {% else %}
    <title>Personal Bubble</title>
    {% endif %}
</head>

<body>

    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
                <a class="navbar-brand mr-4" href="/">Personal Bubble</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                        {% if current_user.is_authenticated %}
                        <a class="nav-item nav-link">Home</a>
                        <a class="nav-item nav-link" href="{{ url_for('lists.list_items') }}">To Do List</a>
                        <a class="nav-item nav-link" href="{{ url_for('videos.temp') }}">Videos</a>
                        {% endif %}

                    </div>
                    <!-- Navbar Right Side -->
                    <div class="navbar-nav">
                        {% if current_user.is_authenticated %}
                        <a class="nav-item nav-link">Account</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                        {% else %}
                        <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </header>

    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
                <!-- the with_categories=true allows for the 'success' class to be passed in -->
                {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                    {{ message }}
                </div>
                {% endfor %}
                {% endif %}
                {% endwith %}
                {% block content %}{% endblock %}
            </div>
        </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

myspace/templates/list.html
{# this is called templated inheritance so that changes only need to be made once #}

<!DOCTYPE html>
<html>

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
    <title>Personal Bubble - {{ title }}</title>
    {% else %}
    <title>Personal Bubble</title>
    {% endif %}
</head>

<body>

    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
                <a class="navbar-brand mr-4" href="/">Personal Bubble</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                        <a class="nav-item nav-link">Home</a>
                        <a class="nav-item nav-link" href="{{ url_for('lists.list_items') }}">To Do List</a>
                        <a class="nav-item nav-link" href="{{ url_for('videos.temp') }}">Videos</a>

                    </div>
                    <!-- Navbar Right Side -->
                    <div class="navbar-nav">
                        {% if current_user.is_authenticated %}
                        <a class="nav-item nav-link">Account</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                        {% else %}
                        <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </header>

    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
                <!-- the with_categories=true allows for the 'success' class to be passed in -->
                {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                    {{ message }}
                </div>
                {% endfor %}
                {% endif %}
                {% endwith %}

                {% for reminder in reminders %}
                {% if reminder.author == current_user %}

                <article class="media content-section">

                    <div class="media-body">
                        <h2><a class="article-title">{{ reminder.title }}</a></h2>
                        <p class="article-content">{{ reminder.content }}</p>
                    </div>
                    <div>
                        <a class="btn btn-secondary btn-sm mt-1 mb-1"
                            href="{{ url_for('lists.update_item', item_id=reminder.id)}}">Update</a>
                        <a class="btn btn-secondary btn-danger btn-sm mt-1 mb-1"
                            href="{{ url_for('lists.delete_item', item_id=reminder.id) }}">Delete</a>

                    </div>
                </article>
                {% endif %}
                {% endfor %}
            </div>

            <div class="col-md-4">
                <div class="content-section">
                    <ul class="list-group">
                        <li class="list-group-item list-group-item-light"><a href="{{ url_for('lists.new_item')}}">Add
                                to List</a>
                        </li>

                    </ul>
                    </p>
                </div>
            </div>

        </div>
    </main>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

myspace/templates/login.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Log In</legend>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span> {{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-control form-control-lg") }}
                {% endif %} </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                {{ form.password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                    <span> {{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.password(class="form-control form-control-lg") }}
                {% endif %} 
            </div>
            <div class="form-check">
                {{ form.remember(class="form-check-input")}}
                {{ form.remember.label(class="form-check-label")}}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
            <small class="text-muted ml-2">
                <!-- # is a link that goes nowhere -->
                <a>Forgot Password?</a>
            </small>
        </div>
    </form>
</div>

<div class="border-top pt-3">
    <small class="text-muted">
        Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
    </small>
</div>
{% endblock content %}

myspace/templates/video.html
{# this is called templated inheritance so that changes only need to be made once #}

<!DOCTYPE html>
<html>

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
    <title>Personal Bubble - {{ title }}</title>
    {% else %}
    <title>Personal Bubble</title>
    {% endif %}
</head>

<body>

    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
                <a class="navbar-brand mr-4" href="/">Personal Bubble</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                        <a class="nav-item nav-link">Home</a>
                        <a class="nav-item nav-link" href="{{ url_for('lists.list_items') }}">To Do List</a>
                        <a class="nav-item nav-link" href="{{ url_for('videos.temp') }}">Videos</a>

                    </div>
                    <!-- Navbar Right Side -->
                    <div class="navbar-nav">
                        {% if current_user.is_authenticated %}
                        <a class="nav-item nav-link">Account</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                        {% else %}
                        <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </header>

    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
                <!-- the with_categories=true allows for the 'success' class to be passed in -->
                {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                    {{ message }}
                </div>
                {% endfor %}
                {% endif %}
                {% endwith %}

                <div class="embed-responsive embed-responsive-16by9">
                    {% if videos[video_id]%}
                    <iframe src="{{ videos[video_id].url }}">
                    </iframe>
                    {% endif %}
                </div>
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center mt-5">
                        {% if video_id == 0 %}
                            {% if count == 1 %}

                            {% else %}
                                <li class="page-item"><a class="page-link"
                                        href="{{url_for('videos.video', video_id=video_id+1)}}">Next</a></li>

                            {% endif %}
                        {% elif not videos[video_id+1] %}
                        <li class="page-item"><a class="page-link"
                                href="{{url_for('videos.video', video_id=video_id-1)}}">Previous</a></li>
                        {% else %}
                        <li class="page-item"><a class="page-link"
                                href="{{url_for('videos.video', video_id=video_id-1)}}">Previous</a></li>
                        <li class="page-item"><a class="page-link"
                                href="{{url_for('videos.video', video_id=video_id+1)}}">Next</a></li>
                        {% endif %}
                    </ul>
                </nav>
            </div>

            <div class="col-md-4">
                <div class="content-section">
                    <ul class="list-group">
                        <li class="list-group-item list-group-item-light">
                            <a href="{{ url_for('videos.new_video')}}">Add Video</a>
                        </li>
                        <li class="list-group-item list-group-item-light">
                            <a href=#>Edit List</a>
                        </li>
                    </ul>
                </div>
                <div class="content-section">
                    {% for video in videos %}

                    <ul class="list-group mt-1 mb-1">
                        <li class="list-group-item list-group-item-dark mb-1 mt-1">
                            <a>{{video.name}}</a>
                            <div style=display:inline-block;float:right>
                                <a class="btn btn-danger btn-sm"
                                    href="{{ url_for('videos.delete_video', video_id=video.id) }}">Delete</a>
                            </div>
                        </li>
                    </ul>
                    {% endfor %}

                </div>
            </div>


        </div>
    </main>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>